"""url_shortner

Revision ID: 66d7e3de609d
Revises: 
Create Date: 2022-08-13 20:54:46.843167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d7e3de609d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_shortners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Long', sa.Text(), nullable=True),
    sa.Column('Short', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_shortners')
    # ### end Alembic commands ###
